### PR TITLE
Bug fixes of checkSolu function

### PR DESCRIPTION
**Pull request by mithun218**
**Related issues:**
#3

### CODE REVIEW

**Comment by peanutfun** [comment]
Why did this PR also remove two test cases?

**Comment by mithun218** [comment]
Because, currently  checkSolu function is unable to check all solutions due
to some simplification problems. We have observed that checkSolu function
cannot verify all the solutions obtained in these two removed test cases.
But, using Maple software we have checked that GiNaCDE reports correct
solutions of these two removed test cases.

**Comment by peanutfun** [comment]
Alright, but this still appears a bit confusing to me. I myself cannot confirm this because I do not have Maple. Could you determine for which types or classes of functions `checkSolu` does not work? What exactly causes the function to fail?

**Comment by mithun218** [comment]
When the `checkSolu` function substitutes the solution in the differential equation and simplifies, then during simplification, the problem comes from `simplify() `function. We explain the cause of the problem below:

 Trigonometric, hyperbolic, or Jacobian functions may be involved in the solutions determined by GiNaCDE.
Actually, the problem occurs when `simplify()` function simplifies trigonometric, hyperbolic or Jacobian functions which may be involved in the solutions.  GiNaCDE is in an inferior stage to simplify such functions. Because to simplify such functions, we have to apply some identities for trigonometric, hyperbolic or Jacobian functions, and I am sorry to say that we have not been able to use these identities of the aforesaid functions so far in the proper way so that the simplification works perfectly for lengthy algebraic expressions.
However, GiNaCDE can simplify simple algebraic expressions (simple means low exponent<4, small number of summands etc.) containing these functions perfectly.

But, when GiNaCDE determines the solutions of NLPDEs and NLODEs, these functions (trigonometric, hyperbolic, or Jacobian) are not involved. So, during determinations of the exact solutions of differential equations, `simplify()` function works perfectly, and the software determines correct solutions. So, the incompleteness of checkSolu functions does not hamper in determining the exact solutions of differential equations.

**Comment by mithun218** [comment]
We are happy to inform you that we have improved `checkSolu` and `simplify` functions to some extent. Now we have examined that GiNaCDE with these improvements can successfully verify the solutions obtained in the above two removed test cases (although it takes some time (~300 Sec in my system) to verify the solutions). Please let me know, will we add these two removed test cases with these improvements?

**Comment by peanutfun** [comment]
Thank you for elaborating! It is great to hear that `checkSolu` is now able to check the removed test cases. But I agree that about 300 sec. is a very long time compared to the usual run times of the GiNaCDE executables, so I would leave these cases out.

**Pull request merged**
