### PR TITLE
Check solutions

### PR DESCRIPTION
**Pull request by mithun218**
Implementation of checkSolu() function to verify computation results and adding manual instructions on how to do so on GiNaCDE, Maple and Mathematica software.

**Related issues**
openjournals/joss-reviews#3885

### CODE REVIEW

**Comment by peanutfun** [comment]
@mithun218, thanks for implementing the `checkSolu` function but I realize now that it does not serve the purpose I hoped it would. In the test cases you added in this PR, `checkSolu` receives a differential equation as input string. However, `desolve` does not return a string. I was hoping for a test case that computes a solution with `desolve`, which is then verified with `checkSolu` in a single executable. Could you implement that?

Notice also that the new test cases have not been added as CMake executables and tests, as I mentioned in #3.

**Comment by mithun218** [comment]
>  I was hoping for a test case that computes a solution with desolve, which is then verified with checkSolu in a single executable. Could you implement that?

I will try to add checkSolu function in test1.cpp to verify the solutions. Will  it be  OK?

**Comment by peanutfun** [comment]
Yes, that would be okay. As I mentioned initially, the purpose of the tests is to verify that GiNaCDE is doing the right thing, at least in some particular cases. So you need to write a test that computes a solution with `desolve`, that is then checked. You can do this check either by substitution, as performed in `checkSolu`, or by comparing the solution against a custom expression that you know should be the solution.

This should be the case for any test you have in this repository. Cases of which you cannot confirm the solution must be removed from the tests.

**Comment by mithun218** [comment]
@peanutfun  Now, all the test files (test1 and test2) compute the solutions with `desolve`, and the solutions are then checked using `checkSolu` function. We have also added the new tests (checkSolutest1 and checkSolutest2) to CMake test executables.
These implementations can be seen from [here](https://github.com/mithun218/GiNaCDE/pull/23).

**Pull request merged**
